spring.application.name=Maintenance

# Server Configuration
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://57.128.222.80:5000/anomaly
spring.data.mongodb.database=anomaly

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
